apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitamoto-otomatik-store
  labels:
    app: kitamoto-otomatik-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kitamoto-otomatik-store
  template:
    metadata:
      labels:
        app: kitamoto-otomatik-store
    spec:
      containers:
      - name: kitamoto-otomatik-store
        image: nikkinicholasromero/kitamoto-otomatik-store
        ports:
        - containerPort: 80
