apiVersion: v1
kind: Service
metadata:
  name: kitamoto-otomatik-store
  labels:
    app: kitamoto-otomatik-store
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: kitamoto-otomatik-store
