apiVersion: v1
kind: Service
metadata:
  name: kitamoto-otomatik-service
  labels:
    app: kitamoto-otomatik-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: kitamoto-otomatik-service
